In [3]:
import numpy as np

# Basic operations

In [7]:
# 1D - Array
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [8]:
# 2D - Array
b = np.array([[1,2,3,9],[4,5,6,7]])
print(b)

[[1 2 3 9]
 [4 5 6 7]]


In [9]:
# 3D - Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#Data types
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [12]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
# np.arrange
np.arange(1,26,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [14]:
# reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# np.zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# np.random
np.random.random((3,4))

array([[0.99587871, 0.83457537, 0.15764496, 0.22307502],
       [0.14399851, 0.9981152 , 0.19203942, 0.84863895],
       [0.80502218, 0.74992933, 0.04423975, 0.73850266]])

In [18]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [19]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes


In [4]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# ndim
a3.ndim

3

In [22]:
# shape
a2.shape

(3, 4)

In [23]:
# size
a2.size

12

In [24]:
# itemsize
a3.itemsize

8

In [5]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
a3

int64
float64
int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Chainging Datatype

In [ ]:
 # astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations


In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Scalar Operations
# Arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# Relational Operators
a1 > 6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
# Vector operations 
# Arithmetic 
a2 * a1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 66.,   1.,  14.],
       [ 47.,  10.,  35.],
       [ 27., 100.,  41.]])

In [ ]:
# max/min/sum/product
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1,axis=1)

array([   924.,  16450., 110700.])

In [ ]:
# mean/median/std/var
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(592.0)

In [ ]:
# trigonometric functions
np.sin(a1)
np.cos(a1)
1/np.sin(a1)

array([[-37.66314636,   1.18839511,   1.0094817 ],
       [  8.0923746 ,  -1.83816396,  -2.33545183],
       [  1.04561394,  -1.97485753,  -6.30426917]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log ans exponents
np.log(a1)
np.exp(a1)

array([[4.60718663e+28, 2.71828183e+00, 1.20260428e+06],
       [2.58131289e+20, 2.20264658e+04, 1.58601345e+15],
       [5.32048241e+11, 2.68811714e+43, 6.39843494e+17]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[28., 56., 16.],
       [45., 20., 54.]])

# Indexing & Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2[1][2]

np.float64(6.0)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1][0][-1]

np.int64(5)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2[0,:]

array([0., 1., 2., 3.])

In [ ]:
a2[:,2]

array([ 2.,  6., 10.])

In [ ]:
a2[2,1:3]

array([ 9., 10.])

In [ ]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [ ]:
a2[0::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [ ]:
a2[1,0::3]

array([4., 7.])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,:,:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,2,1]

np.int64(16)

In [ ]:
a3[2,0,2]

np.int64(20)

In [ ]:
a3[::2,0,0:3:2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [ ]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape

In [ ]:
# transpose

In [ ]:
np.transpose(a2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [ ]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [ ]:
# ravel

In [ ]:
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
# horizontal stacking

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4, a5, a4, a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking

In [ ]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]